name: loga_parameshwari
description: This application help to see pooja and events held on the powerfull
  Loga Parameshwari Temple Ramassery.
publish_to: 'none'
version: 1.13.7+9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.1
  cached_network_image: ^3.0.0
  cloud_firestore: ^2.3.0
  datetime_picker_formfield: ^2.0.0
  firebase_analytics: ^8.1.2
  firebase_auth: ^2.0.0
  firebase_core: ^1.3.0
  firebase_messaging: ^10.0.3
  firebase_storage: ^9.0.0
  flutter_staggered_grid_view: ^0.4.0
  google_fonts: ^2.1.0
  google_mobile_ads: ^0.13.2
  intl: ^0.17.0
  multi_image_picker: ^4.8.1
  package_info: ^2.0.2
  share: ^2.0.4
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.9

dev_dependencies: null

flutter:
  uses-material-design: true
  assets:
    - images/god.webp
    - images/icon.png
