name: loga_parameshwari
description: This application help to see pooja and events held on the powerfull
  Loga Parameshwari Temple Ramassery.
publish_to: 'none'
version: 1.13.7+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0
  cached_network_image: ^3.0.0
  cloud_firestore: ^1.0.3
  cross_connectivity: ^3.0.2
  datetime_picker_formfield: ^2.0.0
  firebase_analytics: ^7.1.1
  firebase_core: ^1.0.2
  firebase_auth: ^2.0.0
  firebase_messaging: ^10.0.3
  firebase_storage: ^8.0.1
  flutter_restart: ^0.0.3
  flutter_staggered_grid_view: ^0.4.0 
  google_fonts: ^2.0.0
  intl: ^0.17.0
  multi_image_picker: ^4.8.0
  share: ^2.0.1
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.3
  google_mobile_ads: ^0.13.2

dev_dependencies: null

flutter:
  uses-material-design: true
  assets:
    - images/god.webp
