name: Perform CD
on:
  push:
    tags:
      - '*'

jobs:
  continuous_deployment:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "11.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ vars.FLUTTER_VERSION }}
          channel: "stable"

      - name: Get Flutter Dependancy
        run: flutter pub get

      - name: Decode keystore files
        run: |
          echo $KEY_JKS_BASE64 | base64 --decode > key.jks
          
          touch key.properties
          echo "storePassword=$KEY_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEY_PASSWORD" >> key.properties
          echo "keyAlias=$KEY_ALIAS" >> key.properties
          echo "storeFile=${{github.workspace}}/key.jks" >> key.properties

          mv key.properties android/key.properties
        env:
          KEY_JKS_BASE64: ${{ secrets.KEY_JKS_BASE64 }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS : ${{ secrets.KEY_ALIAS }}

      
      - name: Build Android App
        run: flutter build appbundle --release
      
      - name: Upload apk to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/bundle/release/app-release.aab
          overwrite: true

  notification_success:
    if: success()
    needs: [continuous_deployment]
    runs-on: ubuntu-latest
    steps:
      - name: Send Success Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Continuous Deployment Completed Successfully!!!

            User: ${{ github.actor }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}


  notification_failure:
    if: failure()
    needs: [continuous_deployment]
    runs-on: ubuntu-latest
    steps:
      - name: Send Failure Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Continuous Deployment Failed!!!

            User: ${{ github.actor }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}